### ISSUE TITLE
双开mumu12模拟器，两个端口分别同时连接MAA和FGOPY,会冲突导致互相断联

### ISSUE THREAD

**Issue by zhhq255762** [hgjazhgj/FGO-py#112]
### 在提问之前...

- [X] 我已经搜索了现有的 issues 和 discussions
- [X] 我已经阅读了 readme 中除版本记录以外的所有内容
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 这个问题出现在最新版的 FGO-py 上
- [X] 这个问题出现了至少3次
- [X] 我使用过旧版的 FGO-py 并且没有出现过这个问题

### 描述你的问题

双开mumu12模拟器，两个端口分别同时连接MAA和FGOPY,会冲突导致互相断联。
以前同时用过两个脚本可以，但是现在好像都不行了。
不知道是扫描端口冲突还是ADB冲突？

### 如何复现

1. 前往 '...'
2. 点击 '...'
3. 滑动到 '...'
4. 出现问题

### 预期行为

是不是端口可以改成手动输入的固定IP端口，不需要扫描能解决这个问题？

### 相关 Logs

```Text
[2023-08-08 18:57:47,414][DEBUG]<airtest.core.android.adb> G:\Games\FGO-py.cn.portable\Python39\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 127.0.0.1:16416 shell screencap -p
[2023-08-08 18:57:48,232][DEBUG]<airtest.utils.nbsp> [airtouch_server]b''
[2023-08-08 18:57:48,233][DEBUG]<airtest.utils.nbsp> [rotation_server]b''
[2023-08-08 18:57:48,273][ERROR]<fgo.Gui> 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "G:\Games\FGO-py.cn.portable\FGO-py\FGO-py\fgoGui.py", line 84, in f
    func()
  File "G:\Games\FGO-py.cn.portable\FGO-py\FGO-py\fgoKernel.py", line 42, in wrapper
    with lock:return func(*args,**kwargs)
  File "G:\Games\FGO-py.cn.portable\FGO-py\FGO-py\fgoKernel.py", line 399, in __call__
    if Detect(.3,.3).isMainInterface():
  File "G:\Games\FGO-py.cn.portable\FGO-py\FGO-py\fgoDetect.py", line 179, in __init__
    super().__init__()
  File "G:\Games\FGO-py.cn.portable\FGO-py\FGO-py\fgoDetect.py", line 46, in __init__
    self.im=self.screenshot()
  File "G:\Games\FGO-py.cn.portable\FGO-py\FGO-py\fgoAndroid.py", line 66, in screenshot
    def screenshot(self):return cv2.resize(super().snapshot()[self.render[1]+self.border[1]:self.render[1]+self.render[3]-self.border[1],self.render[0]+self.border[0]:self.render[0]+self.render[2]-self.border[0]],(1280,720),interpolation=cv2.INTER_CUBIC)
TypeError: 'NoneType' object is not subscriptable
[2023-08-08 18:57:48,926][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended
[2023-08-08 18:57:53,660][DEBUG]<airtest.core.android.adb> G:\Games\FGO-py.cn.portable\Python39\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe devices
[2023-08-08 18:57:59,567][DEBUG]<airtest.core.android.adb> G:\Games\FGO-py.cn.portable\Python39\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 127.0.0.1:16416 get-state
[2023-08-08 18:58:04,622][DEBUG]<airtest.core.android.adb> G:\Games\FGO-py.cn.portable\Python39\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 127.0.0.1:16416 connect 127.0.0.1:16416
[2023-08-08 18:58:04,653][INFO]<airtest.core.android.adb> connected to 127.0.0.1:16416


[2023-08-08 18:58:04,653][DEBUG]<airtest.core.android.adb> G:\Games\FGO-py.cn.portable\Python39\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 127.0.0.1:16416 wait-for-device
[2023-08-08 18:58:04,682][DEBUG]<airtest.core.android.adb> G:\Games\FGO-py.cn.portable\Python39\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 127.0.0.1:16416 shell getprop ro.build.version.sdk
[2023-08-08 18:58:11,960][DEBUG]<airtest.core.android.adb> G:\Games\FGO-py.cn.portable\Python39\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 127.0.0.1:16416 shell ls -l /data/local/tmp/rotationwatcher.jar
[2023-08-08 18:58:17,025][DEBUG]<airtest.core.android.adb> G:\Games\FGO-py.cn.portable\Python39\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 127.0.0.1:16416 push G:\Games\FGO-py.cn.portable\Python39\Lib\site-packages\airtest\core\android\static\apks\rotationwatcher.jar /data/local/tmp/rotationwatcher.jar
[2023-08-08 18:58:22,080][ERROR]<airtest.core.android.rotation> Traceback (most recent call last):
  File "G:\Games\FGO-py.cn.portable\Python39\lib\site-packages\airtest\core\android\rotation.py", line 111, in start
    self.setup_server()
  File "G:\Games\FGO-py.cn.portable\Python39\lib\site-packages\airtest\core\android\rotation.py", line 75, in setup_server
    self.install()
  File "G:\Games\FGO-py.cn.portable\Python39\lib\site-packages\airtest\core\android\rotation.py", line 53, in install
    self.adb.push(ROTATIONWATCHER_JAR, self.path_in_android)
  File "G:\Games\FGO-py.cn.portable\Python39\lib\site-packages\airtest\core\android\adb.py", line 467, in push
    self.cmd(["push", local, remote], ensure_unicode=False)
  File "G:\Games\FGO-py.cn.portable\Python39\lib\site-packages\airtest\core\android\adb.py", line 197, in cmd
    raise AdbError(stdout, stderr)
airtest.core.error.AdbError: stdout[b"adb server version (41) doesn't match this client (36); killing...\r\n* daemon started successfully *\r\nadb: error: connect failed: device '127.0.0.1:16416' not found\r\n"] stderr[b'']

[2023-08-08 18:58:22,081][ERROR]<airtest.core.android.rotation> RotationWatcher setup failed, use ADBORI instead.
[2023-08-08 18:58:22,082][DEBUG]<airtest.core.android.adb> G:\Games\FGO-py.cn.portable\Python39\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 127.0.0.1:16416 shell dumpsys SurfaceFlinger
```

### 截图

![image](https://github.com/hgjazhgj/FGO-py/assets/48901967/cde55ddd-62a0-42cd-aa1a-98d71a4b8544)

### 还有别的吗？

https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/5872

MAA好像是支持多开的

### 来点色图

![-357675701](https://github.com/hgjazhgj/FGO-py/assets/48901967/23dfb89a-e549-4404-a53d-39de0dee5974)

**Comment by hgjazhgj** [comment]
- 勾选了`这个问题出现在最新版的 FGO-py 上`, 但是日志和截图并非来自于最新版FGO-py  
- 勾选了`我使用过旧版的 FGO-py 并且没有出现过这个问题`, 但是此问题毫无疑问会出现在旧版FGO-py上

鉴定为来捣乱的
