### ISSUE TITLE
windows下新安装FGO-py with alas报错

### ISSUE THREAD

**Issue by JOYACEpoor** [hgjazhgj/FGO-py#142]
### 在提问之前...

- [X] 我已经搜索了现有的 issues 和 discussions
- [X] 我已经阅读了 readme 中除版本记录以外的所有内容
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 这个问题出现在最新版的 FGO-py 上
- [ ] 这个问题出现了至少3次
- [ ] 我使用过旧版的 FGO-py 并且没有出现过这个问题

### 描述你的问题

cli启动失败

### 如何复现

1. 在使用之前updater.py会报文件编码错误，需要在`open('fgoConst.py')`中指定文件编码`open('fgoConst.py',encoding='utf-8')`
2. 修改后进度条会卡住，无法继续
3. 再次修改launch.bat中的启动命令`python -X utf-8 fgo.py cli --no-color`为`python -X gbk fgo.py cli --no-color`后进度条会跑两次，且进度条不在乱码，但报错
4. 出现问题

### 相关日志

```Text
## Log1

INFO     21:35:10.131 │ : HEAD is now at 6fb7f2c v19.4.0                                                                 
ERROR    21:35:10.133 │ Traceback (most recent call last):                                                               
ERROR    21:35:10.135 │   File "C:\Users\MermaidGirl\Desktop\FGO-py.portable\deploy\updater.py", line 9, in <module>     
ERROR    21:35:10.136 │     with open('fgoConst.py')as f:installed_version=tuple(int(i)for i in                          
         f.readline()[10:-2].split('.'))                                                                                 
ERROR    21:35:10.138 │                                                                         ^^^^^^^^^^^^             
ERROR    21:35:10.139 │ UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 295: illegal multibyte        
         sequence                                                                                                        
INFO     21:35:10.155 │ : Update failed. See above. 

## Log2

INFO     21:41:20.076 │ : HEAD is now at 6fb7f2c v19.4.0                                                                 
INFO     21:41:20.823 │ FGO-py v19.4.0 PID 3216                                                                          
WARNING  21:41:20.824 │ Using Adb in PATH:                                                                               
         C:\Users\MermaidGirl\Desktop\AzurLaneAutoScript\toolkit\Lib\site-packages\adbutils\binaries\adb.EXE             
INFO     21:41:20.847 │ :                                                                                                
INFO     21:41:20.947 │ :   0%|          | 0/406 [00:00<?, ?it/s]                                                        
INFO     21:41:21.048 │ :  17%|█▋        | 68/406 [00:00<00:00, 679.80it/s]                                              
INFO     21:41:21.148 │ :  34%|███▎      | 137/406 [00:00<00:00, 681.80it/s]                                             
INFO     21:41:21.248 │ :  52%|█████▏    | 211/406 [00:00<00:00, 708.29it/s]                                             
INFO     21:41:21.349 │ :  69%|██████▉   | 282/406 [00:00<00:00, 708.95it/s]                                             
INFO     21:41:21.424 │ :  87%|████████▋ | 353/406 [00:00<00:00, 706.79it/s]                                             
INFO     21:41:21.703 │ :                                                                                                
INFO     21:41:21.705 │ :                                                                                                
INFO     21:41:22.092 │ :   0%|          | 0/4 [00:00<?, ?it/s]                                                          
INFO     21:41:22.469 │ :  25%|██▌       | 1/4 [00:00<00:01,  2.57it/s]                                                  
INFO     21:41:22.843 │ :  50%|█████     | 2/4 [00:00<00:00,  2.62it/s]                                                  
INFO     21:41:23.227 │ :  75%|███████▌  | 3/4 [00:01<00:00,  2.64it/s]                                                  
INFO     21:41:23.229 │ : 100%|██████████| 4/4 [00:01<00:00,  2.63it/s]                                                  
INFO     21:41:23.261 │ :                                                                                                
ERROR    21:41:23.263 │ Traceback (most recent call last):                                                               
ERROR    21:41:23.264 │   File "C:\Users\MermaidGirl\Desktop\FGO-py.portable\FGO-py\FGO-py\fgo.py", line 17, in <module> 
ERROR    21:41:23.266 │     case'cli':from fgoCli import main                                                            
ERROR    21:41:23.267 │               ^^^^^^^^^^^^^^^^^^^^^^^                                                            
ERROR    21:41:23.268 │   File "C:\Users\MermaidGirl\Desktop\FGO-py.portable\FGO-py\FGO-py\fgoCli.py", line 309, in      
         <module>                                                                                                        
ERROR    21:41:23.270 │                                                                                                  
         parser_teamup_set_index.add_argument('value',help='on/off',type=str.lower,choices=['on','off'])                 
ERROR    21:41:23.273 │     ^^^^^^^^^^^^^^^^^^^^^^^                                                                      
ERROR    21:41:23.274 │ NameError: name 'parser_teamup_set_index' is not defined. Did you mean: 'parser_teamup_set_'?
```

### 截图

![QQ_1727012112581](https://github.com/user-attachments/assets/39c748fd-db77-4ca4-b53f-6f6fa2e6fd38)
![QQ_1727012399010](https://github.com/user-attachments/assets/d1adcf3c-3d3c-4a35-aedd-4d70ed59d4db)
![QQ_1727012711209](https://github.com/user-attachments/assets/30ce50b3-a076-43ef-b3a9-782f058bb50f)

### 其他

操作系统: Windows10 LTSB2016 in Proxmox VE
FGO-py 版本: v19.4.0
CPU 型号: Intel CC150

### 来点色图

![c3a29c27ba542715ccb35f7a5bc9da80](https://github.com/user-attachments/assets/afec2991-193b-4893-89f7-1a979670b675)

**Comment by hgjazhgj** [comment]
请展示你在「FGO-py设置 - 运行环境 - 启动路径」中填写的内容

**Comment by JOYACEpoor** [comment]
启动路径`C:\Users\MermaidGirl\Desktop\FGO-py.portable\FGO-py\deploy\AzurLaneAutoScript`
btw gui是可以使用且正常的，下图为todesk远程到windows使用完成战斗功能和启动路径内容等
![QQ_1727015987849](https://github.com/user-attachments/assets/f7aa6afd-d517-4fe5-91fd-afce1498cc19)

**Comment by hgjazhgj** [comment]
> 在使用之前updater.py会报文件编码错误，需要在open('fgoConst.py')中指定文件编码open('fgoConst.py',encoding='utf-8')

当前版本示例的portable.launch.bat有误,会更正

> 修改后进度条会卡住，无法继续

我需要进一步检查alas中的相关实现,此问题由本人负责
目测是alas未能正确解码FGO-py的输出
我可能会在近期先在FGO-py侧进行*让他不卡住能运行但是中文乱码*的workaround修复(按理说就算乱码也应该是能够继续运行的

> 再次修改launch.bat中的启动命令python -X utf-8 fgo.py cli --no-color为python -X gbk fgo.py cli --no-color后进度条会跑两次，且进度条不在乱码，但报错

错误的修改方法,这会使得FGO-py不工作

---

这个-X utf8是python的utf8模式,意图是一站式地解决本软件所有的潜在的编码问题,并实现向python3.15的平滑过渡

**Comment by JOYACEpoor** [comment]
收到了，感谢回复

**Comment by hgjazhgj** [comment]
> (按理说就算乱码也应该是能够继续运行的

对于你提供的log2中最终的报错,已在8月25日v19.4.1中修复,但是一直没有推送到终端用户
请在明天上午再次尝试更新

**Comment by w211691** [comment]
> hi，情况更新了。我删除原文件夹后重新解压了一次portable并运行了一次fgopy 成功更新到了v19.4.1，但我注意到updater.py处仍然报文件编码错误
> 
> ```
> INFO     14:31:04.188 │ : HEAD is now at 648f43a v19.4.1 fix #136 #139                                                       
> ERROR    14:31:04.191 │ Traceback (most recent call last):                                                                   
> ERROR    14:31:04.192 │   File "C:\Users\MermaidGirl\Desktop\FGO-py.portable\deploy\updater.py", line 9, in <module>         
> ERROR    14:31:04.194 │     with open('fgoConst.py')as f:installed_version=tuple(int(i)for i in                              
>          f.readline()[10:-2].split('.'))                                                                                     
> ERROR    14:31:04.195 │                                                                         ^^^^^^^^^^^^                 
> ERROR    14:31:04.197 │ UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 295: illegal multibyte sequence   
> INFO     14:31:04.219 │ : Update failed. See above.                                                                          
> ```
> 
> ![QQ_1727073393302](https://private-user-images.githubusercontent.com/31247549/369770830-f3715065-460b-4996-a19b-0fc0f7fcc9c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4ODQxMDYsIm5iZiI6MTczMDg4MzgwNiwicGF0aCI6Ii8zMTI0NzU0OS8zNjk3NzA4MzAtZjM3MTUwNjUtNDYwYi00OTk2LWExOWItMGZjMGY3ZmNjOWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA5MDMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MjM2NTdlNjU4MmY4NzE5NDFjZmI4YjEyOGNhYmQ3YzM5ODk1NmUyMmJkYTRkMTYxNDA0NzRiZmVhZWZlYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.y5YvaM86YdbWNq5klC7IjTqmo2XfrkMC8czk55dc-Hk)
> 
> 指定文件编码后继续运行，但如上文中仍然乱码，并无法继续运行 ![QQ_1727073509674](https://private-user-images.githubusercontent.com/31247549/369771186-8e27065c-c60a-4ff7-b62a-75f540a577e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4ODQxMDYsIm5iZiI6MTczMDg4MzgwNiwicGF0aCI6Ii8zMTI0NzU0OS8zNjk3NzExODYtOGUyNzA2NWMtYzYwYS00ZmY3LWI2MmEtNzVmNTQwYTU3N2UxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA5MDMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZjcyNWQxODQ1YmE0MTU3OTkyOGEzZjY2N2EyNGY2NmZlNWNiYWRjMzdkOWYyNzk0MTY4MWQyZWEwNDQyNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.l-FslnHTrhQZy-nvI0sPT_a8n5OG9HfwB9Dq8JUVI0g)
> 
> 最后，当我修改launch.bat的启动命令中的utf8为不指定则可以启动（根据上文中标记为错误的修改方法，但实际上也可以成功运行，only `-X utf8`失败） ![QQ_1727073662932](https://private-user-images.githubusercontent.com/31247549/369772002-e5bc1270-72cb-41f9-88c4-49d012d0a8f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4ODQxMDYsIm5iZiI6MTczMDg4MzgwNiwicGF0aCI6Ii8zMTI0NzU0OS8zNjk3NzIwMDItZTViYzEyNzAtNzJjYi00MWY5LTg4YzQtNDlkMDEyZDBhOGY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA5MDMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYmZkZWE1YWZiODMwZTNmMDY5Njk4NTc3MzJkOWE0MThlNmU1YjZjYmJiZDEzZDZmYzkyMzlkZDdkNTdlMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SiUf5WB4O9MLmhc7rRN9-JcYZT0ek5FyJb0XbFBAIu4)

碰到了一样的问题，最新版本：
═════════════════════════════════════════════════════════════════════════════════════════════
                                            START                                            
═════════════════════════════════════════════════════════════════════════════════════════════
INFO     17:18:33.101 │ [Server] cn                                                          
INFO     17:18:33.112 │ Bind task ['General', 'Alas', 'Fpy']                                 
INFO     17:18:33.115 │ Save config ./config\FGOFGO.fpy.json,                                
         Commission.Scheduler.Enable=True, Research.Scheduler.Enable=True,                   
         Reward.Scheduler.Enable=True                                                        
INFO     17:18:33.135 │ Bind task ['General', 'Alas', 'Fpy']                                 
INFO     17:18:33.137 │ Bind task ['General', 'Alas', 'FpyBenchmark', 'Fpy']                 
════════════════════════════════════ SHOW DEPLOY CONFIG ═════════════════════════════════════
INFO     17:18:33.155 │ SHOW DEPLOY CONFIG                                                   
INFO     17:18:33.157 │ Repository: git://git.lyoko.io/AzurLaneAutoScript                    
INFO     17:18:33.159 │ PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple                 
INFO     17:18:33.161 │ Language: zh-CN                                                      
INFO     17:18:33.163 │ Rest of the configs are the same as default                          
INFO     17:18:33.251 │ : D:\SoftWare\FGOPY\FGO-py\deploy\AzurLaneAutoScript\                
INFO     17:18:34.227 │ : HEAD is now at 648f43a v19.4.1 fix #136 #139                       
ERROR    17:18:34.254 │ Traceback (most recent call last):                                   
ERROR    17:18:34.258 │   File "D:\SoftWare\FGOPY\deploy\updater.py", line 9, in <module>    
ERROR    17:18:34.260 │     with open('fgoConst.py')as f:installed_version=tuple(int(i)for i 
         in f.readline()[10:-2].split('.'))                                                  
ERROR    17:18:34.263 │                                                                      
         ^^^^^^^^^^^^                                                                        
ERROR    17:18:34.265 │ UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position   
         295: illegal multibyte sequence                                                     
INFO     17:18:34.303 │ : Update failed. See above.

**Comment by hgjazhgj** [comment]
我希望我最近能有时间来考察此问题（

**Comment by w211691** [comment]
> 我希望我最近能有时间来考察此问题（

奇怪的BUG，单独使用FGOPY没有任何问题

**Comment by hgjazhgj** [comment]
这并不奇怪,原因是我在v19.4.0引入了PEP 540,但未在alas中更改编码

**Comment by NightVigour** [comment]
> hi，情况更新了。我删除原文件夹后重新解压了一次portable并运行了一次fgopy 成功更新到了v19.4.1，但我注意到updater.py处仍然报文件编码错误
> 
> ```
> INFO     14:31:04.188 │ : HEAD is now at 648f43a v19.4.1 fix #136 #139                                                       
> ERROR    14:31:04.191 │ Traceback (most recent call last):                                                                   
> ERROR    14:31:04.192 │   File "C:\Users\MermaidGirl\Desktop\FGO-py.portable\deploy\updater.py", line 9, in <module>         
> ERROR    14:31:04.194 │     with open('fgoConst.py')as f:installed_version=tuple(int(i)for i in                              
>          f.readline()[10:-2].split('.'))                                                                                     
> ERROR    14:31:04.195 │                                                                         ^^^^^^^^^^^^                 
> ERROR    14:31:04.197 │ UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 295: illegal multibyte sequence   
> INFO     14:31:04.219 │ : Update failed. See above.                                                                          
> ```
> 
> ![QQ_1727073393302](https://private-user-images.githubusercontent.com/31247549/369770830-f3715065-460b-4996-a19b-0fc0f7fcc9c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwOTc2ODIsIm5iZiI6MTczNDA5NzM4MiwicGF0aCI6Ii8zMTI0NzU0OS8zNjk3NzA4MzAtZjM3MTUwNjUtNDYwYi00OTk2LWExOWItMGZjMGY3ZmNjOWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDEzNDMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MGU5N2UzNzI3MmJkMTczZjM1MjE0OWI4OWZjYjQwMjNkYzI2Njk3NGVjMGU0MjYwMDRjNjFlMzdkMDUxNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5BV9vPO3aCeQ0V8cGJaR1B89wYavFpWoP4gBGOAkQK8)
> 
> 指定文件编码后继续运行，但如上文中仍然乱码，并无法继续运行 ![QQ_1727073509674](https://private-user-images.githubusercontent.com/31247549/369771186-8e27065c-c60a-4ff7-b62a-75f540a577e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwOTc2ODIsIm5iZiI6MTczNDA5NzM4MiwicGF0aCI6Ii8zMTI0NzU0OS8zNjk3NzExODYtOGUyNzA2NWMtYzYwYS00ZmY3LWI2MmEtNzVmNTQwYTU3N2UxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDEzNDMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzYTBhMjg3ZDdmMDk5ODhjOGVlMWNlOTQzYjE3MTRhMjcxZWFhZDdhNmI2Mzc3Nzg1MGY3NmE5MjYzM2VmZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cKSprJqmuD49lc8ewcIrxQs43zaLb4qgEyQvCujiC4o)
> 
> 最后，当我修改launch.bat的启动命令中的utf8为不指定则可以启动（根据上文中标记为错误的修改方法，但实际上也可以成功运行，only `-X utf8`失败） ![QQ_1727073662932](https://private-user-images.githubusercontent.com/31247549/369772002-e5bc1270-72cb-41f9-88c4-49d012d0a8f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwOTc2ODIsIm5iZiI6MTczNDA5NzM4MiwicGF0aCI6Ii8zMTI0NzU0OS8zNjk3NzIwMDItZTViYzEyNzAtNzJjYi00MWY5LTg4YzQtNDlkMDEyZDBhOGY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDEzNDMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiOWViMjM3NjZlZTY0NGY3MTBkNjYxMzUxYzg3NGY2MGU1NWMyYzljYzdmZGU4OTlmMWI0YjhjMmFmN2Y4YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x3LYrObW2XYxLVYFpRn0waB5GmwdBnlDInOBS-eN-JE)

确实把-X utf8删了和读取编码fgoconst的时候加了utf8编码就可以正常在alas跑完性能测试

**Comment by mog-yep** [comment]
感谢，这个pep45我可以怎么自己在alas中更改呢？

**Comment by hgjazhgj** [comment]
Fixed in LmeSzinc/AzurLaneAutoScript#4645
