### ISSUE TITLE
遇到一个bug cv2 error

### ISSUE THREAD

**Issue by predinpure** [hgjazhgj/FGO-py#74]
### 在提问之前...

- [X] 我已经搜索了现有的 issues 和 discussions
- [X] 我已经阅读了readme中除版本记录以外的所有内容
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 FGO-py

### 描述你的问题

运行在macOS下 
选关卡正常，选助战正常，进入战斗报错

cv2.error: OpenCV(4.6.0) /Users/runner/work/opencv-python/opencv-python/opencv/modules/imgproc/src/templmatch.cpp:768: error: (-215:Assertion failed) _img.size().height >= _templ.size().height && _img.size().width >= _templ.size().width in function 'matchTemplateMask'

### 如何复现

1.gui
2.肝
3.执行到进入战斗
4.报错

### 预期行为

执行正常

### 相关 Logs

```Text
OpenCV(4.6.0) /Users/runner/work/opencv-python/opencv-python/opencv/modules/imgproc/src/templmatch.cpp:768: error: (-215:Assertion failed) _img.size().height >= _templ.size().height && _img.size().width >= _templ.size().width in function 'matchTemplateMask'
Traceback (most recent call last):
  File "/Users/p/Documents/FGO-py-master/FGO-py/fgoGui.py", line 94, in f
    func(*args,**kwargs)
  File "/Users/p/Documents/FGO-py-master/FGO-py/fgoKernel.py", line 322, in __call__
    if self.battleProc():
  File "/Users/p/Documents/FGO-py-master/FGO-py/fgoKernel.py", line 252, in __call__
    self.turnProc(self.turn)
  File "/Users/p/Documents/FGO-py-master/FGO-py/fgoKernel.py", line 99, in __call__
    self.servant=[(lambda x:(x,)+servantData.get(x,()))(Detect.cache.getFieldServant(i))for i in range(3)]
  File "/Users/p/Documents/FGO-py-master/FGO-py/fgoKernel.py", line 99, in <listcomp>
    self.servant=[(lambda x:(x,)+servantData.get(x,()))(Detect.cache.getFieldServant(i))for i in range(3)]
  File "/Users/p/Documents/FGO-py-master/FGO-py/fgoLogging.py", line 11, in <lambda>
    def logit(logger,level=logging.DEBUG):return lambda func:wraps(func)(lambda*args,**kwargs:(lambda x:(logger.log(level,' '.join((func.__name__,str(x)[:100].split('\n',1)[0]))),x)[-1]if x is not None else x)(func(*args,**kwargs)))
  File "/Users/p/Documents/FGO-py-master/FGO-py/fgoDetect.py", line 129, in getFieldServant
    def getFieldServant(self,pos):return(lambda img,cls:min((numpy.min(cv2.matchTemplate(img,i[...,:3],cv2.TM_SQDIFF_NORMED,mask=i[...,3])),no)for no,(_,portrait,_)in servantImg.items()if servantData[no][0]==cls[0]for i in portrait)[1]if cls else 0)(self._crop((120+318*pos,421,207+318*pos,490)),self.getFieldServantClassRank(pos))
  File "/Users/p/Documents/FGO-py-master/FGO-py/fgoDetect.py", line 129, in <lambda>
    def getFieldServant(self,pos):return(lambda img,cls:min((numpy.min(cv2.matchTemplate(img,i[...,:3],cv2.TM_SQDIFF_NORMED,mask=i[...,3])),no)for no,(_,portrait,_)in servantImg.items()if servantData[no][0]==cls[0]for i in portrait)[1]if cls else 0)(self._crop((120+318*pos,421,207+318*pos,490)),self.getFieldServantClassRank(pos))
  File "/Users/p/Documents/FGO-py-master/FGO-py/fgoDetect.py", line 129, in <genexpr>
    def getFieldServant(self,pos):return(lambda img,cls:min((numpy.min(cv2.matchTemplate(img,i[...,:3],cv2.TM_SQDIFF_NORMED,mask=i[...,3])),no)for no,(_,portrait,_)in servantImg.items()if servantData[no][0]==cls[0]for i in portrait)[1]if cls else 0)(self._crop((120+318*pos,421,207+318*pos,490)),self.getFieldServantClassRank(pos))
cv2.error: OpenCV(4.6.0) /Users/runner/work/opencv-python/opencv-python/opencv/modules/imgproc/src/templmatch.cpp:768: error: (-215:Assertion failed) _img.size().height >= _templ.size().height && _img.size().width >= _templ.size().width in function 'matchTemplateMask'
```

### 来点色图

nbnb我也想要

抱歉刚才提交没看清楚就issues了

**Comment by hgjazhgj** [comment]
你需要提供更多的日志,比如直接上传完整的日志文件,或者至少是当场战斗的部分

**Comment by predinpure** [comment]
麻烦你了
>上传了日志
[Log_2022-08-22_01.33.38.txt](https://github.com/hgjazhgj/FGO-py/files/9389703/Log_2022-08-22_01.33.38.txt)

**Comment by hgjazhgj** [comment]
你场上的从者是哪几个
这个问题每次进入战斗都出现吗
之前的版本能不能正常使用

**Comment by predinpure** [comment]
> 你场上的从者是哪几个
> 这个问题每次进入战斗都出现吗
> 之前的版本能不能正常使用

1.上场的从者依次是水武藏，阿拉什，剑北斋。
2.这个问题每次都会出现，换了几个队伍一样触发。
3.在这个系统没试过较早之前版本，近两次更新才开始用。在win系统下没遇到这个问题。

**Comment by hgjazhgj** [comment]
请确认你的问题是否每次都出在getFieldServant上
如果是,请提供一张出错时的通过本项目创建的游戏截图
如果不是,那便可能是偶发的截图错误,请告知模拟器型号,但是每次都「一进入战斗就报错」也太奇怪了,请告知你使用的模拟器型号

**Comment by predinpure** [comment]
>请确认你的问题是否每次都出在getFieldServant上
每次都是出在getFieldServant上
>截图
[screenshot.pdf](https://github.com/hgjazhgj/FGO-py/files/9395836/screenshot.pdf)
>日志
[Log_2022-08-22_23.27.48.txt](https://github.com/hgjazhgj/FGO-py/files/9395841/Log_2022-08-22_23.27.48.txt)

**Comment by hgjazhgj** [comment]
请提供一张出错时的通过本项目创建的游戏截图

**Comment by predinpure** [comment]
好的
>上传了「截图」
![Uploading Capture_2022-08-23_00.30.14.048.png…]()

**Comment by hgjazhgj** [comment]
图片没有上传成功,请重新提交

**Comment by predinpure** [comment]
好的
>上传了「截图」
![Capture_2022-08-23_00 30 14 048](https://user-images.githubusercontent.com/20659524/185975792-f95a1432-0fdc-41dd-b1b3-b8e5a25e3310.png)

**Comment by hgjazhgj** [comment]
测试没有发现任何问题...
请确认你没有改动任何代码与资源,比如git status只应显示配置文件和助战模板的更改

**Comment by predinpure** [comment]
我确认确定没有做任何修改...
刚拉下来最新的9.6.2问题解决了...
原因还是不清楚，请确认你有做哪些更新...
抱歉占用了你很多时间，非常感谢！
